### ISSUE TITLE
NPE in Formation.isFrontCar

### ISSUE THREAD

**Issue by anatawa12** [anatawa12/RTM-bug-reporting#7]
RTM 2.4.21_40

プレイヤー付近に連結した列車がある場合に`Formation.isFrontCar`内でぬるぽすることがあります

サーバーサイドで起きるとフリーズし、クライアントサイドで起きるとクラッシュします。

サーバーサイドのフリーズ時のログ：[latest.log](https://github.com/anatawa12/RTM-bug-reporting/files/6054268/latest.log)

クライアントサイドのクラレポ：[crash-2021-02-27_20.32.54-server.txt](https://github.com/anatawa12/RTM-bug-reporting/files/6054291/crash-2021-02-27_20.32.54-server.txt)

```
[20:19:32] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:773) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) ~[chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
Caused by: java.lang.NullPointerException
	at jp.ngt.rtm.entity.train.util.Formation.isFrontCar(Formation.java:397) ~[Formation.class:?]
	at jp.ngt.rtm.entity.train.EntityTrainBase.updateMovement(EntityTrainBase.java:252) ~[EntityTrainBase.class:?]
	at jp.ngt.rtm.entity.vehicle.EntityVehicleBase.onVehicleUpdate(EntityVehicleBase.java:268) ~[EntityVehicleBase.class:?]
	at jp.ngt.rtm.entity.train.EntityTrainBase.onVehicleUpdate(EntityTrainBase.java:223) ~[EntityTrainBase.class:?]
	at jp.ngt.rtm.entity.vehicle.EntityVehicleBase.func_70071_h_(EntityVehicleBase.java:216) ~[EntityVehicleBase.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:1996) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832) ~[oo.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:1958) ~[amu.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1762) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) ~[MinecraftServer.class:?]
	... 4 more
```

**Comment by anatawa12** [comment]
https://twitter.com/kakerigawa/status/1365624974275346432?s=20
